final/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('pacientes/', include('pacientes.urls')),
    path('turnos/', include('turnos.urls')),
]

pacientes/urls.py
from django.urls import path
from . import views

app_name = 'pacientes'
urlpatterns = [
    path("", views.index, name="index"),
    path("ver/<id>", views.ver, name="ver")
]

turnos/urls.py
from django.urls import path
from . import views

app_name = 'turnos'
urlpatterns = [
    path("", views.index, name="index"),
    path("reservar/", views.reservar, name="reservar"),
    path("modificar/<id>/", views.modificar_turno, name="modificar_turno"),
    path("eliminar/<id>/", views.eliminar_turno, name="eliminar_turno")
]

usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout")
]

pacientes/models.py
from django.conf import settings
from django.db import models
from django.core.validators import RegexValidator

# Create your models here.
class Paciente(models.Model):
    nombre = models.CharField(max_length=64)
    apellido = models.CharField(max_length=64)
    dni = models.CharField(unique=True, max_length=8, validators=[RegexValidator(r'^\d{1,10}$')])

    def __str__(self):
        return f"{self.dni}: {self.nombre} {self.apellido}"

# Create your models here.
class Historia(models.Model):
    consulta = models.CharField(max_length=100)
    fecha = models.DateField()
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    medico = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.fecha}: {self.paciente} - {self.medico}  {self.consulta}"

turnos/models.py
from django.conf import settings
from django.db import models
from pacientes import models as pacientes_models
from django.utils import timezone

# Create your models here.
class Turno(models.Model):
    fecha = models.DateTimeField(default=timezone.now)
    paciente = models.ForeignKey(pacientes_models.Paciente, on_delete=models.CASCADE)
    medico = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    asistio = models.BooleanField(null=True)

    def __str__(self):
        return f"Turno: {self.fecha} -- Paciente: {self.paciente}, Médico: {self.medico}"

usuarios/models.py
from django.db import models

# Create your models here.

pacientes/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Paciente, Historia

class HistoriaPacienteForm(forms.ModelForm):

    paciente = forms.ModelChoiceField( 
        queryset=Paciente.objects.all(),
        widget=forms.HiddenInput(attrs={'readonly': 'readonly'})
    )
    medico = forms.ModelChoiceField( 
        queryset=User.objects.all(),
        widget=forms.HiddenInput(attrs={'readonly': 'readonly'})
    )
    

    class Meta: 
        model = Historia
        fields = '__all__'

turnos/forms.py
from django import forms
from .models import Turno

class TurnoAltaForm(forms.ModelForm):

    class Meta: 
        model = Turno
        fields = ['fecha', 'paciente', 'medico']
        #fields = '__all__'

pacientes/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Paciente, Historia
from .forms import HistoriaPacienteForm

# Create your views here.
def index(request):
    data = {
        'pacientes': Paciente.objects.all()
    }
    return render(request, 'pacientes.html', data)

# Create your views here.
def ver(request, id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('usuarios:login'))
   
    if request.method == 'POST':
        formulario = HistoriaPacienteForm(data= request.POST)
        if formulario.is_valid():
            formulario.save()
        else:
            data['form']  = formulario

    paciente = get_object_or_404(Paciente, id=id)
    historia = Historia.objects.filter(paciente=paciente)
    data = {
        'paciente': paciente,
        'historia': historia,
        'form': HistoriaPacienteForm(initial={'paciente': paciente, 'medico': request.user})
    }
    return render(request, 'paciente.html', data)

turnos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import Group, User
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import TurnoAltaForm
from .models import Turno
from pacientes.models import Paciente

# Create your views here.
def index(request):
    data = {
        'turnos': Turno.objects.all()
    }
    return render(request, 'turnos.html', data)

def reservar(request):    
    data = {
        'form': TurnoAltaForm()
    }
    if request.method == 'POST':
        formulario = TurnoAltaForm(data= request.POST)
        if formulario.is_valid():
            formulario.save()
            data['mensaje'] = "Turno reservado correctamente"
        else:
            data['form']  = formulario
    return render(request, 'reservar.html', data)

def modificar_turno(request, id):
    turno = get_object_or_404(Turno, id=id)
    data = {
        'form' : TurnoAltaForm(instance=turno)
    }
    if request.method == 'POST':
        formulario = TurnoAltaForm(data= request.POST, instance=turno)
        if formulario.is_valid():
            formulario.save()
            #return HttpResponseRedirect(reverse('turnos:index'))
            return redirect(to='turnos:index')

        #sino valida mando a editar con los datos del form
        data['form']  = formulario
    
    return render(request, 'editar-turno.html', data)

def eliminar_turno(request, id):
    turno = get_object_or_404(Turno, id=id)
    turno.delete()
    return redirect(to='turnos:index')

usuarios/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group


# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('usuarios:login'))
    
    group_secretaria = Group.objects.get(name="secretaria").user_set.all()
    group_medicos = Group.objects.get(name="medicos").user_set.all()

    if request.user in group_secretaria:
        return render(request, 'index-secretaria.html')
    elif request.user in group_medicos:
        return render(request, 'index-medicos.html')
    else:
        return render(request, 'index.html')


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user:
            login(request, user)
            return HttpResponseRedirect(reverse('usuarios:index'))
        else:
            return render(request, 'login.html', {
                "mensaje" : "Credenciales NO válidas"
            })
            
    return render(request, 'login.html')

def logout_view(request):
    logout(request)
    return render(request, 'login.html', {
        'mensaje' : 'Usted se ha desconectado exitosamente'
    })

pacientes/templates/layout.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block header %}{% endblock %}
   
</head>
<body>
    {% block body %}    
    {% endblock %}
</body>
</html>

pacientes/templates/paciente.html
{% extends 'layout.html' %}
{% block header %}
    <title>Pacientes :: historia</title>
{% endblock  %}

{% block body %}
    <h1>Datos del paciente</h1>
    <ul>
        <li>Paciente: {{ paciente.nombre }} - {{ paciente.apellido }}</li>
        <li>DNI: {{ paciente.dni }}</li>
    </ul>

    <h2>Historia Clínica</h2>
    {% for h in historia %} 
        <hr> 
        <p> 
            Fecha: {{ h.fecha }} - Atendido por: {{ h.medico }} 
            <br> Historia: {{ h.consulta }}
        </p>          
    {% empty %} 
        <p>No hay Historia clínica cargada para este paciente</p>
    {% endfor %} 
    
    {% if perms.pacientes.add_historia %}    
    <hr>
    <h5>Agregar a la historia clínica</h5>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form }}
        <input type="hidden" name="medico" value="{{ user.id }}" readonly="readonly" id="id_medico">
        <input type="submit" value="Guardar" />
    </form>
    {% endif %}
{% endblock  %}

pacientes/templates/pacientes.html
{% extends 'layout.html' %}
{% block header %}
    <title>Pacientes :: listado</title>
{% endblock  %}

{% block body %}
    <table border="1">
        <thead>
            <tr>
                <td>DNI:</td>
                <td>Nombre:</td>
                <td>Apellido:</td>
                <td>Historia C.</td>
            </tr>
        </thead>
        <tbody>
            {% for p in pacientes %} 
                <tr>
                    <td>{{ p.dni }}</td>
                    <td>{{ p.nombre }}</td>
                    <td>{{ p.apellido }}</td>
                    <td><a href="{% url 'pacientes:ver' p.id %}"> Ver</a></td>
                </tr>                
            {% empty %} 
                <tr>
                    <td colspan="4">No hay pacientes cargados</td>
                </tr>
            {% endfor %} 
        </tbody>
    </table> 
{% endblock  %}

turnos/templates/editar-turno.html
{% extends 'layout.html' %}
{% block header %}
    <title>Turnos :: Editar</title>
{% endblock  %}

{% block body %}
    {% if perms.turnos.change_turno %}

        <h1>Editar  Turno</h1>

        <form action="" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Guardar Modificación">
        </form>

        {% if mensaje  %}
        <div>{{ mensaje }}</div>
        {% endif %}
    {% endif %}
    <a href="{% url 'turnos:index' %}">Ver turnos</a>
   
{% endblock  %}

turnos/templates/layout.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block header %}{% endblock %}
   
</head>
<body>
    {% block body %}    
    {% endblock %}
</body>
</html>

turnos/templates/reservar.html
{% extends 'layout.html' %}
{% block header %}
    <title>Turnos :: Reservar</title>
{% endblock  %}

{% block body %}
    <h1>Resrvar Turno</h1>
    {% if mensaje  %}
        <div>{{ mensaje }}</div>
        <a href="{% url 'turnos:index' %}">Ver turnos</a>
    {% endif %}

    <form action="" method="POST">
        {% csrf_token %}
        <label for="fecha">Fecha</label>
        <input type="datetime" name="fecha">
        <label for="paciente">Paciente</label>
        <select name="paciente">
            <option value=""></option>
            {% for paciente in pacientes%}
                <option value="{{paciente.id}}"> {{paciente}} </option>
            {% endfor %}
            
        </select>
        <label for="medico">Médico</label>
        <select name="medico">
            <option value=""></option>
            {% for medico in medicos%}
                <option value="{{medico.id}}"> {{medico}} </option>
            {% endfor %}
            
        </select>
        <input type="submit" value="Guardar">
    </form>
   
{% endblock  %}

turnos/templates/turnos.html
{% extends 'layout.html' %}
{% block header %}
    <title>Turnos :: listados</title>
{% endblock  %}

{% block body %}
    <table border="1">
        <thead>
            <tr>
                <td>Fecha:</td>
                <td>Paciente:</td>
                <td>Médico:</td>
                <td>
                    {% if perms.turnos.add_turno %}
                    <a href="{% url 'turnos:reservar' %}">+ Turno</a>
                    {% endif %}
                </td>
            </tr>
        </thead>
        <tbody>
            {% for turno in turnos %} 
                {% if perms.pacientes.add_historia %}
                    {% if user.id == turno.medico.id %}
                    <tr>
                        <td>{{ turno.fecha }}</td>
                        <td>{{ turno.paciente }} {{ turno.paciente.id }}</td>
                        <td>{{ turno.medico }}</td>
                        <td>
                            {% if perms.turnos.view_turno %}
                            <a href="{% url 'pacientes:ver' turno.paciente.id %}"> Ver</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endif %}
                {% else %}
                <tr>
                    <td>{{ turno.fecha }}</td>
                    <td>{{ turno.paciente }} {{ turno.paciente.id }}</td>
                    <td>{{ turno.medico }}</td>
                    <td>
                        {% if perms.turnos.change_turno %}
                            <a href="{% url 'turnos:modificar_turno' turno.id %}">Edit</a>
                        {% endif %}
                        {% if perms.turnos.delete_turno %}
                            <a href="{% url 'turnos:eliminar_turno' turno.id %}">Del</a>
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
            {% empty %} 
                <tr>
                    <td colspan="4">No hay turnos cargados</td>
                </tr>
            {% endfor %} 
        </tbody>
    </table> 
{% endblock  %}

usuarios/templates/index-medicos.html
{% extends 'layout.html' %}
{% block header %}
    <title>Usuarios Médico: Bienvenido</title>
{% endblock  %}

{% block body %}
    <nav>
        <ul>
            <li><a href="#">Turnos</a></li>
            <li><a href="{% url 'usuarios:logout' %}">Logout</a></li>
        </ul>
    </nav>
    <h1>Bienvenido Médico</h1>    
    <ul>
        <li>Nombre: {{request.user.username }}</li>
        <li>Apellido: {{request.user.lastname }}</li>
        <li>Email: {{request.user.email }}</li>
    </ul>
{% endblock  %}

usuarios/templates/index-secretaria.html
{% extends 'layout.html' %}
{% block header %}
    <title>Usuarios Secretaria:: Bienvenido</title>
{% endblock  %}

{% block body %}

    <nav>
        <ul>
            <li><a href="{% url 'turnos:index' %}">Turnos</a></li>
            <li><a href="{% url 'usuarios:logout' %}">Logout</a></li>
        </ul>
    </nav>

    <h1>Bienveda Secretaria</h1>    

    <ul>
        <li>Nombre: {{request.user.username }}</li>
        <li>Apellido: {{request.user.lastname }}</li>
        <li>Email: {{request.user.email }}</li>
    </ul>

{% endblock  %}

usuarios/templates/index.html
{% extends 'layout.html' %}
{% block header %}
    <title>Usuarios :: Bienvenido</title>
{% endblock  %}
{% block body %}    
    <nav>
        <ul>
            <li><a href="{% url 'usuarios:logout' %}">Logout</a></li>
        </ul>
    </nav>
    <h1>Bienvenido, </h1>
    <ul>
        <li>Nombre: {{request.user.username }}</li>
        <li>Apellido: {{request.user.lastname }}</li>
        <li>Email: {{request.user.email }}</li>
    </ul>
{% endblock  %}

usuarios/templates/login.html
{% extends 'layout.html' %}
{% block header %}
    <title>Usuarios :: Login</title>
{% endblock  %}

{% block body %}

{% if mensaje %}
    <div>{{ mensaje }}</div>
{% endif %}

<form action="{% url 'usuarios:login' %}" method="POST">
    {% csrf_token %}
    <label for="username">Usuario</label>
    <input type="text" name="username" placeholder="Usuario">
    <label for="password">Password</label>
    <input type="password" name="password" placeholder="Password">
    <input type="submit" value="Ingresar">
</form>
{% endblock  %}

usuarios/templates/usuarios.html
{% extends 'layout.html' %}
{% block header %}
    <title>Usuarios :: usuarios</title>
{% endblock  %}

{% block body %}
usuarios
{% endblock  %}